config/routes.rb
Rails.application.routes.draw do
  resources :events
  resources :venues

end

app/models/venue.rb
class Venue < ActiveRecord::Base

  def self.load_wiki_venues_list
    begin
      wp = WikiCasino.new
      results_hash = wp.parse_casino_list_wiki

      # Find OR Create Venues from Casino names in list
      results_hash.each do |venue_hash|
        if venue_hash[:title]
          venue_update_logger.info("Loading Venue by #{venue_hash[:title]}")
          venue = Venue.find_or_initialize_by(title: venue_hash[:title])

          venue_update_logger.info("    New Venue found.") if venue.new_record?
          # update attributes of attributes found
          venue.update_attributes(venue_hash)

          venue_update_logger.info("    Venue Updated")
        end
      end
    rescue Exception => e
      venue_update_logger.error(e.inspect)
      #raise
    end
  end

  def self.update_wiki_venues_attributes
    # Iterate all venues with wiki_url
    # update attributes from wiki page hash
    begin
      wp = WikiCasino.new

      venues = Venue.where("wiki_url LIKE '%wikipedia.org/wiki%'")
      venues.each do |venue|
        venue_update_logger.info("Updating Venue '#{venue.title}' Attributes")
        result_hash = wp.parse_casino_wiki venue.wiki_url, venue.title
        unless result_hash.empty?
          venue.update_attributes(result_hash)
          venue_update_logger.info("    Venue Updated")
        end

      end
    rescue Exception => e
      venue_update_logger.error(e.inspect)
      #raise
    end
  end

  #
  def self.venue_update_logger
    @venue_update_logs ||= Logger.new("#{Rails.root}/log/venue_updates.log")
  end
  def venue_update_logger
    @venue_update_logs ||= Logger.new("#{Rails.root}/log/venue_updates.log")
  end

end

app/controllers/venues_controller.rb
class VenuesController < ApplicationController
  before_action :set_venue, only: [:show, :edit, :update, :destroy]

  # GET /venues
  def index
    @venues = Venue.all
  end

  # GET /venues/1
  def show
  end

  # GET /venues/new
  def new
    @venue = Venue.new
  end

  # GET /venues/1/edit
  def edit
  end

  # POST /venues
  def create
    @venue = Venue.new(venue_params)

    if @venue.save
      redirect_to @venue, notice: 'Venue was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /venues/1
  def update
    if @venue.update(venue_params)
      redirect_to @venue, notice: 'Venue was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /venues/1
  def destroy
    @venue.destroy
    redirect_to venues_url, notice: 'Venue was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_venue
      @venue = Venue.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def venue_params
      params.require(:venue).permit(:title, :headline, :description, :type, :phone, :address1, :address2, :city, :state, :latitude, :longitude, :url, :logo_url, :summary, :attractions, :photo_urls, :opening_date, :number_of_rooms, :theme, :total_gaming_space, :permanent_space, :casino_type, :owner, :renovated_at)
    end
end

app/helpers/venues_helper.rb
module VenuesHelper
end

app/views/venues/_form.html.erb
<%= form_for(@venue) do |f| %>
  <% if @venue.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@venue.errors.count, "error") %> prohibited this venue from being saved:</h2>

      <ul>
      <% @venue.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :headline %><br>
    <%= f.text_field :headline %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :type %><br>
    <%= f.text_field :type %>
  </div>
  <div class="field">
    <%= f.label :phone %><br>
    <%= f.text_field :phone %>
  </div>
  <div class="field">
    <%= f.label :address1 %><br>
    <%= f.text_field :address1 %>
  </div>
  <div class="field">
    <%= f.label :address2 %><br>
    <%= f.text_field :address2 %>
  </div>
  <div class="field">
    <%= f.label :city %><br>
    <%= f.text_field :city %>
  </div>
  <div class="field">
    <%= f.label :state %><br>
    <%= f.text_field :state %>
  </div>
  <div class="field">
    <%= f.label :latitude %><br>
    <%= f.text_field :latitude %>
  </div>
  <div class="field">
    <%= f.label :longitude %><br>
    <%= f.text_field :longitude %>
  </div>
  <div class="field">
    <%= f.label :url %><br>
    <%= f.text_field :url %>
  </div>
  <div class="field">
    <%= f.label :logo_url %><br>
    <%= f.text_field :logo_url %>
  </div>
  <div class="field">
    <%= f.label :summary %><br>
    <%= f.text_area :summary %>
  </div>
  <div class="field">
    <%= f.label :attractions %><br>
    <%= f.text_area :attractions %>
  </div>
  <div class="field">
    <%= f.label :photo_urls %><br>
    <%= f.text_area :photo_urls %>
  </div>
  <div class="field">
    <%= f.label :opening_date %><br>
    <%= f.text_field :opening_date %>
  </div>
  <div class="field">
    <%= f.label :number_of_rooms %><br>
    <%= f.text_field :number_of_rooms %>
  </div>
  <div class="field">
    <%= f.label :theme %><br>
    <%= f.text_field :theme %>
  </div>
  <div class="field">
    <%= f.label :total_gaming_space %><br>
    <%= f.text_field :total_gaming_space %>
  </div>
  <div class="field">
    <%= f.label :permanent_space %><br>
    <%= f.text_field :permanent_space %>
  </div>
  <div class="field">
    <%= f.label :casino_type %><br>
    <%= f.text_field :casino_type %>
  </div>
  <div class="field">
    <%= f.label :owner %><br>
    <%= f.text_field :owner %>
  </div>
  <div class="field">
    <%= f.label :renovated_at %><br>
    <%= f.datetime_select :renovated_at %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/venues/edit.html.erb
<h1>Editing Venue</h1>

<%= render 'form' %>

<%= link_to 'Show', @venue %> |
<%= link_to 'Back', venues_path %>

app/views/venues/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Venues</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Headline</th>
      <th>Description</th>
      <th>Type</th>
      <th>Phone</th>
      <th>Address1</th>
      <th>Address2</th>
      <th>City</th>
      <th>State</th>
      <th>Latitude</th>
      <th>Longitude</th>
      <th>Url</th>
      <th>Logo url</th>
      <th>Summary</th>
      <th>Attractions</th>
      <th>Photo urls</th>
      <th>Opening date</th>
      <th>Number of rooms</th>
      <th>Theme</th>
      <th>Total gaming space</th>
      <th>Permanent space</th>
      <th>Casino type</th>
      <th>Owner</th>
      <th>Renovated at</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @venues.each do |venue| %>
      <tr>
        <td><%= venue.title %></td>
        <td><%= venue.headline %></td>
        <td><%= venue.description %></td>
        <td><%= venue.type %></td>
        <td><%= venue.phone %></td>
        <td><%= venue.address1 %></td>
        <td><%= venue.address2 %></td>
        <td><%= venue.city %></td>
        <td><%= venue.state %></td>
        <td><%= venue.latitude %></td>
        <td><%= venue.longitude %></td>
        <td><%= venue.url %></td>
        <td><%= venue.logo_url %></td>
        <td><%= venue.summary %></td>
        <td><%= venue.attractions %></td>
        <td><%= venue.photo_urls %></td>
        <td><%= venue.opening_date %></td>
        <td><%= venue.number_of_rooms %></td>
        <td><%= venue.theme %></td>
        <td><%= venue.total_gaming_space %></td>
        <td><%= venue.permanent_space %></td>
        <td><%= venue.casino_type %></td>
        <td><%= venue.owner %></td>
        <td><%= venue.renovated_at %></td>
        <td><%= link_to 'Show', venue %></td>
        <td><%= link_to 'Edit', edit_venue_path(venue) %></td>
        <td><%= link_to 'Destroy', venue, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Venue', new_venue_path %>

app/views/venues/new.html.erb
<h1>New Venue</h1>

<%= render 'form' %>

<%= link_to 'Back', venues_path %>

app/views/venues/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @venue.title %>
</p>

<p>
  <strong>Headline:</strong>
  <%= @venue.headline %>
</p>

<p>
  <strong>Description:</strong>
  <%= @venue.description %>
</p>

<p>
  <strong>Type:</strong>
  <%= @venue.type %>
</p>

<p>
  <strong>Phone:</strong>
  <%= @venue.phone %>
</p>

<p>
  <strong>Address1:</strong>
  <%= @venue.address1 %>
</p>

<p>
  <strong>Address2:</strong>
  <%= @venue.address2 %>
</p>

<p>
  <strong>City:</strong>
  <%= @venue.city %>
</p>

<p>
  <strong>State:</strong>
  <%= @venue.state %>
</p>

<p>
  <strong>Latitude:</strong>
  <%= @venue.latitude %>
</p>

<p>
  <strong>Longitude:</strong>
  <%= @venue.longitude %>
</p>

<p>
  <strong>Url:</strong>
  <%= @venue.url %>
</p>

<p>
  <strong>Logo url:</strong>
  <%= @venue.logo_url %>
</p>

<p>
  <strong>Summary:</strong>
  <%= @venue.summary %>
</p>

<p>
  <strong>Attractions:</strong>
  <%= @venue.attractions %>
</p>

<p>
  <strong>Photo urls:</strong>
  <%= @venue.photo_urls %>
</p>

<p>
  <strong>Opening date:</strong>
  <%= @venue.opening_date %>
</p>

<p>
  <strong>Number of rooms:</strong>
  <%= @venue.number_of_rooms %>
</p>

<p>
  <strong>Theme:</strong>
  <%= @venue.theme %>
</p>

<p>
  <strong>Total gaming space:</strong>
  <%= @venue.total_gaming_space %>
</p>

<p>
  <strong>Permanent space:</strong>
  <%= @venue.permanent_space %>
</p>

<p>
  <strong>Casino type:</strong>
  <%= @venue.casino_type %>
</p>

<p>
  <strong>Owner:</strong>
  <%= @venue.owner %>
</p>

<p>
  <strong>Renovated at:</strong>
  <%= @venue.renovated_at %>
</p>

<%= link_to 'Edit', edit_venue_path(@venue) %> |
<%= link_to 'Back', venues_path %>